//! # Generated Reflection Types
//!
//! This module contains the Rust code generated by `tonic-build` from the `reflection.proto` file.
//! It defines the structs and traits required to communicate with standard gRPC reflection servers.
//!
//! *Note: This is strictly for internal use by the `ReflectionClient`.*
//!
#[path = "./generated/grpc.reflection.v1.rs"]
#[allow(clippy::enum_variant_names)]
#[rustfmt::skip]
pub mod reflection_v1;
